server:
  port: ${SERVER_PORT}

exmoney:
  application:
    oauth:
      google:
        api-get-info: https://www.googleapis.com/oauth2/v3/userinfo
      github:
        api-get-info: https://api.github.com/user
        api-valid-token: https://github.com/login/oauth/access_token

spring:
  application:
    name: exmoney
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_DEFAULT_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: abc
            client-secret: dasd
          google:
            client-id: dasd
            client-secret: dsd

  servlet:
    multipart:
      max-request-size: 3MB
      max-file-size: 3MB